PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX fossr: <http://fossr.eu/kg/onto/>

SELECT
?r1 ?r2 (COUNT(*) AS ?common_publications)
WHERE {
  	?r1 dcterms:creator/^dcterms:creator ?r2.
    FILTER(?r1 != ?r2)
}
GROUP BY ?r1 ?r2
ORDER BY DESC(?common_publications)
LIMIT 100